name: child
on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true

jobs:
  # 2 job song song
  build-x64:
    name: build-${{ inputs.channel }}-x64
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "[child:${{ inputs.channel }}:x64] step 1"
      - name: step 2
        run: echo "[child:${{ inputs.channel }}:x64] step 2"
      - name: step 3
        run: echo "[child:${{ inputs.channel }}:x64] step 3"

  build-arm64:
    name: build-${{ inputs.channel }}-arm64
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "[child:${{ inputs.channel }}:arm64] step 1"
      - name: step 2
        run: echo "[child:${{ inputs.channel }}:arm64] step 2"
      - name: step 3
        run: echo "[child:${{ inputs.channel }}:arm64] step 3"

  # Notify sau khi 2 job trên xong
  notify:
    name: notify-${{ inputs.channel }}
    runs-on: ubuntu-latest
    needs: [build-x64, build-arm64]
    if: always()
    steps:
      - run: |
          echo "[child:${{ inputs.channel }}] NOTIFY"
          echo " - build-x64 result: ${{ needs.build-x64.result }}"
          echo " - build-arm64 result: ${{ needs.build-arm64.result }}"
