name: child
on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true

jobs:
  # 2 job song song
  build-x64:
    name: build-${{ inputs.channel }}-x64
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "[child:${{ inputs.channel }}:x64] step 1"
      - name: step 2
        run: echo "[child:${{ inputs.channel }}:x64] step 2"
      - name: step 3
        run: echo "[child:${{ inputs.channel }}:x64] step 3"

  build-arm64:
    name: build-${{ inputs.channel }}-arm64
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "[child:${{ inputs.channel }}:arm64] step 1"
      - name: step 2
        run: echo "[child:${{ inputs.channel }}:arm64] step 2"
      - name: step 3
        run: echo "[child:${{ inputs.channel }}:arm64] step 3"

  # Notify sau khi 2 job trên xong
  notify:
    name: notify-${{ inputs.channel }}
    runs-on: ubuntu-latest
    needs: [build-x64, build-arm64]
    if: always()
    steps:
      - name: Decide message color
        run: |
          if [[ "${{ needs.build-x64.result }}" == "success" && "${{ needs.build-arm64.result }}" == "success" ]]; then
            echo "MSG_COLOR=success" >> $GITHUB_ENV
          else
            echo "MSG_COLOR=danger" >> $GITHUB_ENV
          fi
  
      - name: Push Notification
        uses: phuoc-le/action-lark-notify@main
        with:
          columnsPerRow: 2
          token: ${{ secrets.GITHUB_TOKEN }}
          cardItems: |
            **Workflow**<br>{{GITHUB_WORKFLOW}}
            **Channel**<br>${{ inputs.channel }}
            **Run**<br>[#{{GITHUB_RUN_NUMBER}}]({{GITHUB_JOB_URL}})
            **x64**<br>${{ needs.build-x64.result }}
            **arm64**<br>${{ needs.build-arm64.result }}
            **Repo**<br>[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
            **Ref**<br>[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "Build ${{ inputs.channel }} finished"
          LARK_MESSAGE_SUBTITLE: |
            Overall: ${{ job.status }}
          LARK_MESSAGE_TEMPLATE: ${{ env.MSG_COLOR }}

