on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: phihc116/test-actions@main
        with:
          who-to-greet: Mona the Octocat

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Get HTML URL of current job
        id: get-job-url
        run: |
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)

          echo "$response"

          html_url=$(echo "$response" | jq -r ".jobs[] | select(.name == \"${{ github.job }}\") | .html_url")

          echo "html_url=$html_url"
          echo "GITHUB_JOB_HTML_URL=$html_url" >> $GITHUB_ENV