name: parent
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name (e.g., v1.0.0)"
        required: false

jobs:
  check_client_payload:
    runs-on: ubuntu-latest
    steps:
      - run: echo "[parent] check_client_payload"

  check_and_create_ref:
    runs-on: ubuntu-latest
    needs: check_client_payload
    steps:
      - run: echo "[parent] check_and_create_ref"

  create_gh_release:
    runs-on: ubuntu-latest
    needs: check_and_create_ref
    steps:
      - run: echo "[parent] create_gh_release tag=${{ inputs.tag }}"

  # Hai nhánh gọi child chạy SONG SONG
  trigger-android:
    name: trigger-child-android
    needs: create_gh_release
    uses: ./.github/workflows/child.yml
    with:
      channel: android
    secrets: inherit

  trigger-ios:
    name: trigger-child-ios
    needs: create_gh_release
    uses: ./.github/workflows/child.yml
    with:
      channel: ios
    secrets: inherit
