name: "Auto ACR build push"
run-name: "Build tag [${{ github.event.inputs.tag }}]"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to build and release (e.g., v1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  test-lark:
    name: test lark noti
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tag if not exists
        run: |
          TAG_NAME="${{ github.event.inputs.tag }}"
          EXISTING_TAG=$(git tag -l "$TAG_NAME")
          if [ -z "$EXISTING_TAG" ]; then
            echo "Creating tag: $TAG_NAME"
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          else
            echo "Tag $TAG_NAME already exists. Skipping creation."
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          body: |
            This is an automated release for tag ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify to Lark
        id: hello
        uses: phuoc-le/action-lark-notify@feature/add-extra-columns
        with: 
          columnsPerRow: 2
          token: ${{ secrets.GITHUB_TOKEN }}
          cardItems: |
            **Repo**<br>[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
            **Event**<br>{{GITHUB_EVENT_NAME}}
            **Actor**<br>{{GITHUB_ACTOR}} 
            **Ref**<br>[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
            **Build logs**<br>[{{GITHUB_RUN_ID}}]({{GITHUB_JOB_URL}})
            **Release**<br>[{{GITHUB_RELEASE_TAG_NAME}}]({{GITHUB_RELEASE_URL_BY_BRANCH}})
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "test"
          LARK_MESSAGE_SUBTITLE: |
            Status: test 
          RELEASE_TAG: ${{ github.event.inputs.tag }}

