on:
  workflow_dispatch:

jobs:
  test-lark:
    name: test lark noti
    runs-on: ubuntu-latest

    steps:
      - name: Get current Job ID
        id: get-job-id
        uses: qoomon/actions--context@v4

      - name: Export GITHUB_JOB_ID to env
        run: |
          echo "GITHUB_JOB_ID=${GITHUB_JOB_ID}" >> $GITHUB_ENV
        env:
          GITHUB_JOB_ID: ${{ steps.get-job-id.outputs.job-id }}

      - name: Hello world action step
        id: hello
        uses: phuoc-le/action-lark-notify@feature/add-extra-columns
        with: 
            columnsPerRow: 2
            cardItems: |
                **Repo**\n[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
                **Event**\n{{GITHUB_EVENT_NAME}}
                **Actor**\n{{GITHUB_ACTOR}} 
                **Ref**\n[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
                **Job**\n[{{GITHUB_JOB_ID}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/actions/runs/{{GITHUB_RUN_ID}}/job/{{GITHUB_JOB_ID}})
                **Release**\n[{{RELEASE_TAG}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/releases/tag/{{RELEASE_TAG}})
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "test"
          LARK_MESSAGE_SUBTITLE: |
            Status: test 
          RELEASE_TAG: v1.0.0
          GITHUB_JOB_ID: ${{ env.GITHUB_JOB_ID }}
