on:
  workflow_dispatch: 

jobs:
  test-lark:
    name: test lark noti
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: phuoc-le/action-lark-notify@feature/add-extra-columns
        with: 
            columnsPerRow: 2
            cardItems: |
                **Repo**\n[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
                **Event**\n{{GITHUB_EVENT_NAME}}
                **Actor**\n{{GITHUB_ACTOR}} 
                **Ref**\n[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
                **Job**\n[{{GITHUB_RUN_ID}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/actions/runs/{{GITHUB_RUN_ID}})
                **Release**\n[{{RELEASE_TAG}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/releases/tag/{{RELEASE_TAG}})
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "test"
          LARK_MESSAGE_SUBTITLE: |
            Status: test 
          RELEASE_TAG: v1.0.0


