name: "Auto ACR build push"
run-name: "Build tag [${{ github.event.inputs.tag }}]"

on:
  workflow_dispatch:
  
permissions:
  contents: write
  actions: read  # cần để gọi API lấy danh sách jobs/steps

jobs:
  create_release:
    name: Create tag & GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.gh_release.outputs.url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      # Notify cuối cùng (dù pass/fail đều gửi)
      - name: Notify to Lark (per sub-job)
        if: always()
        uses: ./.github/actions/notify-lark
        with: 
          lark_webhook: ${{ secrets.LARK_WEBHOOK_DEV }}
          github_token: ${{ secrets.GITHUB_TOKEN }} 
