on:
  workflow_dispatch: 

jobs:
  test-lark:
    name: test lark noti
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: phuoc-le/action-lark-notify@5d82d52da6113f3a5c0958a70764463cc8b75d22
        with: 
            columnsPerRow: 2
            cardItems: |
                **Repo**\n[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
                **Event**\n{{GITHUB_EVENT_NAME}}
                **Actor**\n{{GITHUB_ACTOR}} 
                **Ref**\n[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "test"
          LARK_MESSAGE_SUBTITLE: |
            Status: test 

