name: "Auto ACR build push"
run-name: "Build tag [${{ github.event.inputs.tag }}]"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to build and release (e.g., v1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  create_release:
    name: Create tag & GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.gh_release.outputs.url }}
      release_id: ${{ steps.gh_release.outputs.id }}
      upload_url: ${{ steps.gh_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create tag if not exists
        run: |
          TAG_NAME="${{ github.event.inputs.tag }}"
          EXISTING_TAG=$(git tag -l "$TAG_NAME")
          if [ -z "$EXISTING_TAG" ]; then
            echo "Creating tag: $TAG_NAME"
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          else
            echo "Tag $TAG_NAME already exists. Skipping creation."
          fi

      - name: Create GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          body: |
            This is an automated release for tag ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lark_notify:
    name: Notify to Lark
    runs-on: ubuntu-latest
    needs: create_release   # <-- bắt buộc đợi job tạo release xong
    steps:
      - uses: actions/checkout@v4

      - name: Notify to Lark
        id: hello
        uses: phuoc-le/action-lark-notify@refactor/hcphi-refactor-code
        with:
          columnsPerRow: 2
          token: ${{ secrets.GITHUB_TOKEN }}
          cardItems: |
            **Repo**<br>[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
            **Event**<br>{{GITHUB_EVENT_NAME}}
            **Actor**<br>{{GITHUB_ACTOR}}
            **Ref**<br>[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
            **Build logs**<br>[{{GITHUB_RUN_ID}}]({{GITHUB_JOB_URL}})
            **Release**<br>{{GITHUB_RELEASE_URL_BY_BRANCH}}
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "test"
          LARK_MESSAGE_SUBTITLE: |
            Status: test
          RELEASE_TAG: ${{ github.event.inputs.tag }}
