on:
  workflow_dispatch:

jobs:
  test-lark:
    name: test lark noti
    runs-on: ubuntu-latest

    steps:
      - name: Get current Job ID
        id: get-job-id
        uses: qoomon/actions--context@v4

      - name: Export GITHUB_JOB_URL to env
        run: echo "GITHUB_JOB_URL=${GITHUB_JOB_URL}" >> $GITHUB_ENV
        env:
          GITHUB_JOB_URL: ${{ env.GITHUB_JOB_URL }}

      - name: Hello world action step
        id: hello
        uses: phuoc-le/action-lark-notify@feature/add-extra-columns
        with: 
            columnsPerRow: 2
            cardItems: |
                **Repo**<br>[{{GITHUB_REPOSITORY}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}})
                **Event**<br>{{GITHUB_EVENT_NAME}}
                **Actor**<br>{{GITHUB_ACTOR}} 
                **Ref**<br>[{{GITHUB_REF}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/tree/{{GITHUB_REF_NAME}})
                **Job**<br>[{{GITHUB_RUN_ID}}]({{GITHUB_JOB_URL}})
                **Release**<br>[{{RELEASE_TAG}}]({{GITHUB_SERVER_URL}}/{{GITHUB_REPOSITORY}}/releases/tag/{{RELEASE_TAG}})
        env:
          LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
          LARK_MESSAGE_TITLE: "test"
          LARK_MESSAGE_SUBTITLE: |
            Status: test 
          RELEASE_TAG: v1.0.0
          GITHUB_JOB_URL: ${{ env.GITHUB_JOB_URL }}
